#!/usr/bin/env bash
# Stop hook: as a systemMessage, show (when in a git repo) owner/repo,
# branch, and the associated PR URL; plus the last user query and a
# short summary of the response generated by a local Ollama model.

OLLAMA_URL="http://localhost:11434"
OLLAMA_MODEL="qwen2.5-coder:7b"

# JSONL debug log; one object per invocation. Cross-reference entries with
# Claude Code history via session_id / transcript_path.
LOG_DIR="${HOME}/.claude/hooks/logs"
LOG_FILE="${LOG_DIR}/git-repo-info.jsonl"

# Capture stdin (the Stop hook payload) to read the transcript path.
payload=$(cat)
transcript=$(printf '%s' "$payload" | jq -r '.transcript_path // empty')
session_id=$(printf '%s' "$payload" | jq -r '.session_id // empty')
cwd=$(printf '%s' "$payload" | jq -r '.cwd // empty')
started_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Last genuine typed user prompt (skips bash I/O, tool results, meta).
query=""
# Text of this turn's final assistant message.
response=""
if [ -n "$transcript" ] && [ -f "$transcript" ]; then
  query=$(jq -rs 'map(select(.type=="user" and .promptSource!=null) | .message.content | strings) | last // ""' "$transcript" 2>/dev/null)
  # Timestamp of the prompt that started this turn; responses must be newer.
  # This prevents grabbing stale prior-turn text if the current message hasn't
  # been flushed to the transcript yet when the Stop hook fires.
  prompt_ts=$(jq -rc 'select(.type=="user" and .promptSource!=null) | .timestamp' "$transcript" 2>/dev/null | tail -1)
  # Concatenate ALL of this turn's assistant text blocks (intro narration plus
  # the final explanation), not just the last block — which is often a short
  # closing line and makes for a misleading summary.
  collect() {
    jq -rs --arg pts "$prompt_ts" '
      [ .[] | select(.type=="assistant" and (.timestamp > $pts))
            | .message.content[]? | select(.type=="text") | .text ]
      | join("\n\n")' "$transcript" 2>/dev/null
  }
  # Poll until the turn is fully flushed — the transcript's last entry is the
  # assistant's final message — so no trailing text block is missed.
  for _ in $(seq 1 25); do
    if [ "$(tail -1 "$transcript" | jq -r '.type // empty' 2>/dev/null)" = "assistant" ]; then
      response=$(collect); [ -n "$response" ] && break
    fi
    sleep 0.2
  done
  [ -z "$response" ] && response=$(collect)
fi

# Summarize the response with the local model (skip if unavailable/empty).
summary=""
if [ -n "$response" ]; then
  # Cap input length to keep summarization fast.
  response=$(printf '%s' "$response" | cut -c1-6000)
  req=$(jq -n --arg model "$OLLAMA_MODEL" --arg text "$response" '{
    model: $model,
    prompt: ("Below is an assistant'"'"'s response in a coding session. In one or two sentences, state specifically what it did, found, or concluded. Be factual and concrete; do not start with \"The assistant\". Output only the summary:\n\n" + $text),
    stream: false,
    options: {num_predict: 80, temperature: 0.2}
  }')
  ollama_start=$(date +%s)
  summary=$(curl -s --max-time 20 "$OLLAMA_URL/api/generate" -d "$req" 2>/dev/null \
    | jq -r '.response // empty' | tr '\n' ' ' | sed -E 's/^ +//; s/ +$//')
  ollama_ms=$(( ($(date +%s) - ollama_start) * 1000 ))
fi

# Git context (silent when not in a repo).
repo=""; branch=""; pr=""
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  branch=$(git branch --show-current 2>/dev/null)
  remote=$(git remote get-url origin 2>/dev/null)
  repo=$(printf '%s' "$remote" | sed -E 's#^git@[^:]+:##; s#^https?://[^/]+/##; s#\.git$##')
  if command -v gh >/dev/null 2>&1; then
    pr=$(gh pr view --json url -q .url 2>/dev/null)
  fi
fi

# Append a structured debug record (best-effort; never blocks output).
mkdir -p "$LOG_DIR" 2>/dev/null && \
jq -nc \
  --arg ts "$started_at" \
  --arg session_id "$session_id" \
  --arg transcript "$transcript" \
  --arg cwd "$cwd" \
  --arg repo "$repo" --arg branch "$branch" --arg pr "$pr" \
  --arg q "$query" --arg response "$response" --arg summary "$summary" \
  --argjson ollama_ms "${ollama_ms:-0}" \
  '{ts: $ts, session_id: $session_id, transcript: $transcript, cwd: $cwd,
    repo: $repo, branch: $branch, pr: $pr, query: $q,
    response_len: ($response | length), response: $response,
    summary: $summary, ollama_ms: $ollama_ms}' \
  >> "$LOG_FILE" 2>/dev/null

jq -n --arg repo "$repo" --arg branch "$branch" --arg pr "$pr" \
      --arg q "$query" --arg s "$summary" '
  ([ (if $repo   == "" then empty else "Repo: "    + $repo   end),
     (if $branch == "" then empty else "Branch: "  + $branch end),
     (if $pr     == "" then empty else "PR: "      + $pr     end) ] | join("\n")) as $git
  | [ (if $git == "" then empty else $git end),
      (if $q   == "" then empty else "Query: "   + $q end),
      (if $s   == "" then empty else "Summary: " + $s end) ]
  | select(length > 0)
  | {systemMessage: ("\n\n" + join("\n\n"))}'
